#!/bin/bash

set -e

lines=$(cat `find ./ -path ./libgdl -prune -o -path ./_Ressources -prune -o -type f ! -name "pugi*" -iname "*.cpp" -o ! -name "pugi*" -iname "*.h*"` 2> /dev/null | wc -l)
echo "Project line count : $lines"

echo ""

export LD_LIBRARY_PATH=libgdl/libs

time make

echo "";

if [ "$1" == "--gui" ]||[ "$2" == "--gui" ]; then
	if [ "$1" == "-d" ]||[ "$2" == "-d" ]; then
		valgrind ./bomberman --gui
	else
		./bomberman --gui
	fi
else
	if [ "$1" == "-d" ]||[ "$2" == "-d" ]; then
		valgrind ./bomberman
	else
		./bomberman
	fi
fi

set +e
