#!/bin/bash

set -e

lines=$(cat `find ./ -path ./libs -prune -o -path ./libgdl -prune -o -path ./_Ressources -prune -o -type f ! -name "pugi*" -iname "*.cpp" -o ! -name "pugi*" -iname "*.h?*"` 2> /dev/null | wc -l)
lines_xml=$(cat `find ./*/* -name "*.xml"` 2> /dev/null | wc -l)
echo "Project line count : $lines"
echo "XML line count : $lines_xml"

echo ""

export LD_LIBRARY_PATH=libgdl/libs

time make

echo "";

if [ "$1" == "--gui" ]||[ "$2" == "--gui" ]; then
	if [ "$1" == "-d" ]||[ "$2" == "-d" ]; then
		valgrind ./bomberman
	else
		./bomberman
	fi
else
	if [ "$1" == "-d" ]||[ "$2" == "-d" ]; then
		valgrind ./bomberman
	else
		./bomberman
	fi
fi

set +e
